{% set name = "fusesoc" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5b7bf203901dd33362dc0f1e64028ea01e8d9cd8a6de401e10d609baf7ae34e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools_scm
  run:
    - python >=3.7
    - edalize >=0.4.1
    - pyparsing
    - pyyaml
    - simplesat >=0.8.0

test:
  imports:
    - fusesoc

about:
  home: https://github.com/olofk/fusesoc/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: FuseSoC is a package manager and a set of build tools for FPGA/ASIC development

extra:
  recipe-maintainers:
    - hmaarrfk
