{% set version = "2.4.2" %}

package:
  name: fusesoc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/f/fusesoc/fusesoc-{{ version }}.tar.gz
  sha256: 5b7bf203901dd33362dc0f1e64028ea01e8d9cd8a6de401e10d609baf7ae34e0

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - fusesoc = fusesoc.main:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - edalize >=0.4.1
    - pyparsing
    - pyyaml
    - simplesat >=0.8.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - fusesoc

about:
  home: https://github.com/olofk/fusesoc/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: FuseSoC is a package manager and a set of build tools for FPGA/ASIC development

extra:
  recipe-maintainers:
    - hmaarrfk
