{% set name = "fusesoc" %}
{% set version = "1.9.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c8f6183847622dddea4857cb747c01ae0d8fc233103e05084a971dd0a481b464
  patches:
    # These patches have been accepted in the master branch
    - remove_jsonschema_dependency.patch
    - 249-avoid_yaml_load_deprecation_warning.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - edalize >=0.1.3
    - ipyxact >=0.2.3
    - pyparsing
    - pytest >=3.3.0
    - pyyaml
    - simplesat >=0.8.0

test:
  imports:
    - fusesoc

about:
  home: https://github.com/olofk/fusesoc/
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'FuseSoC is a package manager and a set of build tools for FPGA/ASIC development'

extra:
  recipe-maintainers:
    - hmaarrfk
