travis:
  secure:
    BINSTAR_TOKEN: dv828GowfIhs0W+cHyEbi9LmJoS4yzdp0NK9aFiPh2Z1FBBpui9RFXtKuG/wzZGiuLEFvBeYg7Kv+Is0mO9NE0CWKdroHqs1D98QU3Eicv1qoYAuFMDJZ8dSlk4XSAOyWBfoYDLvqPxbruaRdeUENMFvGUqfqYJtt0wmn0X6yw/+Zi2XgB8OPLsM5jaWGC76DUqJ1b4Fh1Ku7J8jxJA6QFTWBkuTniBUWKoQdZWESpCZWaysTFn+yKFOwW78BFM17fMAkN8yK2omHWN75FJC4HxN0hGIuEe/CyFZEeM5OU1rbYYokLj3fFmM70VomJwuAn8MxSG57Y2SjwwRfIjtM0nHeE6vthOhIwVXwTDYFRbqUMXCgZbYAHYC3v7jqvpmgpE1D1UZGZZwVgRZ61eJ+nhCYpqUa31V1gMn2ipPux49EMaUSRh8NAAIfm2TjoCtc1OCxqHr7bKmxAg6JGBC77Db6Kq5RtijMXH09BfXKsaatzROBnsJvEFVsyS1+rqs8AUfd3dF82tojRsHMrvSqpcREbETttNKud3xnGey9TGX1jeQ1aacSf6CWKgiKGFSIG/fzY+zoa+7eKiVvLjdev/n9YHoOwmusPxrZRsSN8n6WsWjGlk4OLTj00oLyd+ZaU54N3Ldq28G/T4ReoVvujlj6tCUrAaF/PAC93+n8iM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
